wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.8
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703284588.98732
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.8.8
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
param:
  desc: null
  value: 89321
model:
  desc: null
  value: "EugiFormer(\n  (preprocess): Sequential(\n    (0): Linear(in_features=40,\
    \ out_features=80, bias=True)\n    (1): GELU(approximate='none')\n    (2): Linear(in_features=80,\
    \ out_features=40, bias=True)\n  )\n  (pos_encoder): PositionalEncoding(\n   \
    \ (dropout): Dropout(p=0.1, inplace=False)\n  )\n  (mhas): ModuleList(\n    (0-5):\
    \ 6 x MultiheadAttention(\n      (out_proj): NonDynamicallyQuantizableLinear(in_features=40,\
    \ out_features=40, bias=True)\n    )\n  )\n  (ffnns): ModuleList(\n    (0-5):\
    \ 6 x Sequential(\n      (0): Linear(in_features=40, out_features=80, bias=True)\n\
    \      (1): GELU(approximate='none')\n      (2): Linear(in_features=80, out_features=40,\
    \ bias=True)\n    )\n  )\n  (bns1): ModuleList(\n    (0-5): 6 x BatchNorm1d(40,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n  )\n  (bns2):\
    \ ModuleList(\n    (0-5): 6 x BatchNorm1d(40, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n  )\n  (dropout): Dropout(p=0.0, inplace=False)\n\
    \  (postprocess): Sequential(\n    (0): Linear(in_features=40, out_features=80,\
    \ bias=True)\n    (1): GELU(approximate='none')\n    (2): Linear(in_features=80,\
    \ out_features=1, bias=True)\n  )\n)"
